# Generated by Django 6.0.6 on 2026-06-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="reserved_stock",
            field=models.PositiveIntegerField(
                default=0, help_text="Quantity reserved for pending/confirmed orders."
            ),
        ),
    ]
